name: Build and Deploy
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    environment: dev

    permissions:
      id-token: write
      contents: read

    env:
      AWS_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
      DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Set up environment
        run: |
          env > .env
          echo "Enviorment setup complete"

      - name: Build Vite app
        run: npm run build

      - name: Login to Amazon S3
        id: login-s3
        uses: aws-actions/configure-aws-credentials@v2

      - name: Sync files to S3
        run: |
          aws s3 sync dist/ s3://${{ env.S3_BUCKET_NAME }} --delete

      # Invalidate CloudFront cache (optional)
      - name: Invalidate CloudFront Cache
        if: ${{ env.DISTRIBUTION_ID != '' }}
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ env.DISTRIBUTION_ID }} \
            --paths "/*"
